name: Notes Application CI Pipeline
# create a CI pipeline based on the assignment specification
# remember to commit often

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
      - feature/*

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 17.x
        uses: actions/setup-node@v3
        with:
          node-version: '17'
      - name: Install dependencies
        run: npm clean-install --prefix src
      - name: Run linter
        run: npm run test-lint --prefix src > reports/lint-reports.xml
      - if: success() || failure()
        name: Upload linting results
        uses: actions/upload-artifact@v3
        with:
          name: lint-results-${{ github.sha }}
          path: reports/lint-reports.xml

  unit-tests:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 17.x
        uses: actions/setup-node@v3
        with:
          node-version: '17'
      - name: Install dependencies
        run: npm clean-install --prefix src
      - name: Run unit tests
        run: npm run test-unit --prefix src > reports/unit-test-reports.xml
      - if: success() || failure()
        name: Upload unit test results
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-results-${{ github.sha }}
          path: reports/unit-test-reports.xml
      - if: github.ref == 'refs/heads/main' && (success() || failure())
        name: Create deployable artifact
        run: npm run pack --prefix src
      - if: github.ref == 'refs/heads/main' && (success() || failure())
        name: Upload deployable artifact
        uses: actions/upload-artifact@v3
        with:
          name: deployable-artifact-${{ github.sha }}
          path: src/*.tgz

  integration-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 17.x
        uses: actions/setup-node@v3
        with:
          node-version: '17'
      - name: Install dependencies
        run: npm clean-install --prefix src
      - name: Download deployable artifact
        uses: actions/download-artifact@v3
        with:
          name: deployable-artifact-${{ github.sha }}
          path: src
      - name: Start MongoDB container
        run: docker run --name mongo -p 27017:27017 -d mongo:latest
      - name: Run integration tests
        run: npm run test-integration --prefix src > reports/integration-test-reports.xml
      - name: Stop MongoDB container
        run: docker stop mongo
      - if: success() || failure()
        name: Upload integration test results
        uses: actions/upload-artifact@v3
        with:
          name: integration-test-results-${{ github.sha }}
          path: reports/integration-test-reports.xml